### ISSUE TITLE
Clash with wowchemy cite.html shortcode - document how to solve that?

### ISSUE THREAD

**Issue by LukasWallrich** [loup-brun/hugo-cite#54] opened 2021-10-25 18:00 UTC
There is a cite.html shortcode in the wowchemy-hugo-themes (https://github.com/wowchemy/wowchemy-hugo-themes/blob/main/wowchemy/layouts/shortcodes/cite.html). In my setup, that masked the hugo-cite version, which took a while to troubleshoot. I am still not sure what the best action to take would be - for now, I deleted the unneeded cite.html, but it might come back with future updates.

Probably the only thing that can be done about that is to add a warning/hint to the installation instructions?

**Comment by HughP** [comment] 2021-10-25 21:15
I think I filed a ticket with this effect about a year or so ago. Yes it
should be solved... lots of wowchemy users should be using this theme too.

**Comment by loup-brun** [comment] 2022-02-16 23:28
Duplicate of #23 – will look into it soon

**Closed as completed by loup-brun** 2022-02-16 23:28 UTC
